redis:
    image: redis

mee6:
    image: mee6-bot
    links:
        - redis
    environment:
        - REDIS_URL=redis://redis/
        - MEE6_TOKEN=...

mee6-web:
    image: mee6-web
    links:
        - redis
    environment:
        - REDIS_URL=redis://redis/
        - OAUTH2_CLIENT_ID=...
        - OAUTH2_CLIENT_SECRET=...
        - OAUTH2_REDIRECT_URI=...
        - SECRET_KEY=...
    expose:
        - 5000

proxy:
    image: jwilder/nginx-proxy
